version: '3.7'
services:
    web:
        build:
            context: .
        ports:
            - 5000:5000
        volumes:
            - ./:/app
        environment:
            - FLASK_APP=./app.py
    mysqldb:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=1
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
volumes:
    mysql:
    mysql_config:

        